version: '3.7'

services:
  web:
    build:
      context: ./employee-todo-list-app
      dockerfile: Dockerfile
    environment:
      - API_URL=http://api:80
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
  api:
    build:
      context: ./employee-todo-list-api
      dockerfile: Dockerfile
    environment:
      - "FFOS_TEST_DbSettings__ConnectionString=${MONGO_CONNECTION_STRING}"
    ports:
      - "5000:80"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - app-network
volumes:
  mongo-data:

networks:
  app-network:
